### ISSUE TITLE
Add hash of gzip file to task requests?

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero-server#129]
See discussion here.

https://github.com/gcp/leela-zero/pull/1429#discussion_r188338729

It would allow autogtp to check for valid gzip file of a network hash without decompressing the file. If we calculate them on server as needed and store in a Map, we'd only need to do it once per gzip (per server restart) which is much less than once per autogtp startup/download.

**Comment by marcocalignano** [comment]
Is this a real problem or will this implemented?

**Comment by roy7** [comment]
@Mardak Would you be willing to do this? Or do we think it's better to have the autogtp client maybe switch to a gzip streaming interface to do the hash would forking a separate process?

Here's an example perhaps of what that looks like client side.

https://stackoverflow.com/questions/3722192/how-do-i-use-gzipstream-with-system-io-memorystream

**Comment by Mardak** [comment]
@rchs819 any thoughts on how to update all the endpoints that give a network hash to also include the gzip hash?

**Comment by Mardak** [comment]
We probably want to keep get-task backwards compatible with older clients, so probably safest to just add an extra field by appending "_gzip_hash" so white_hash_gzip_hash, black_hash_gzip_hash, hash_gzip_hash

**Comment by roy7** [comment]
@marcocalignano Which specific branch should someone use to test your gzip hash related code?

@mardak Or someone with a fast GPU, can you test his branch out to be sure it works with matches?

https://github.com/gcp/leela-zero/pull/1429#discussion_r188338729

**Comment by roy7** [comment]
Ok @marcocalignano tested using this and it seems to be working fine. He downloaded some match requests and uploaded some results, I assume using gzip_hash to be sure the files were okay without needing to ungzip them and process them for hashes?
