### ISSUE TITLE
Why can't I run node server.js?

### ISSUE THREAD

**Issue by chunjiongzhang** [leela-zero/leela-zero-server#210]
when i run node server.js

it will show that :
fs.js:122
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:509:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)
    at Object.<anonymous> (/home/zcj/leela-zero-server/server.js:94:28)
    at Module._compile (internal/modules/cjs/loader.js:703:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:714:10)
    at Module.load (internal/modules/cjs/loader.js:613:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:552:12)
    at Function.Module._load (internal/modules/cjs/loader.js:544:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:756:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:865:3)

My server configuration is that 
node -v
v11.0.0-pre

mongo --version
MongoDB shell version: 3.2.21

npm --version
6.4.1

ubuntu    16.0.2

and  we have created the auth_key file...

Please help me, I have studied it for many days.

**Comment by roy7** [comment]
Hmm, I'm not sure, but when I tried running it locally myself I got an error at the same spot but a different error.

> node server.js
> fs.js:113
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, open '/home/roy/code/leela-zero-server/task_secret'
> 

Making a task_secret file fixed it for me. I'm not sure what directory or file it's trying to read that it throwing that error for you. Try running it with sudo in case it's a permissions problem?

**Comment by chunjiongzhang** [comment]
Sir, can you write a window and ubuntu installation tutorial? Specific to each step of the installation instructions.

**Comment by chunjiongzhang** [comment]
Sir, I'd like to know where Leela has uploaded the chess score to server since it finished selfplay. I haven't found it in mongodb. Is the chess score still in SGF format?

**Comment by roy7** [comment]
If you are running a local server and using that to upload to instead of the main server, the games should be in db. From your command line if you run 'mongo' and then type ' db.games.find().limit(1);' it should show you a game.

Be careful if you are altering the client that you aren't uploading the games to the main real server, sometimes people make that mistake. When the client uploads you should see some result messages on the client side as well as the console output of the server process.

**Comment by roy7** [comment]
@chunjiongzhang Did you ever get this sorted out?

**Comment by roy7** [comment]
Closing for age.

**Comment by chunjiongzhang** [comment]
Yes, the problem has been solved. Thank you

**Comment by chunjiongzhang** [comment]
Yes, the problem has been solved. Thank you @roy7
