### ISSUE TITLE
How to connect the networks with server 

### ISSUE THREAD

**Issue by Superkidd** [leela-zero/leela-zero-server#217]
Hello

When I run server.js , I have a log like:

```
best_network_hash_promise begins
           rss
           heapTotal
           heapUsed
           external
Streams prepared
           rss
           heapTotal
           heapUsed
           external
0 networks
0 LZ games, 0 ELF games
listening on 8080
No clients found with sufficient rate data ....etc
```
I have done all the requirements for running server.js. As a final step, would you explain how to  add networks by running this server?

And,  I have more question. If I change the Data path of the autoGTP to the my server, How it works

**Comment by roy7** [comment]
Yeah we probably need to include a sample network and a couple mongodb commands or something to help people jump start a brand new server (for testing or personal use). Is there a sample curl command to upload to the server in the readme? If so you'll need to upload 1 network to get the server going with, then your autogtp that connects to your local server (and not the real server, please be careful with that) it should snag the network and start doing selfplay games to upload.

**Comment by roy7** [comment]
The README doesn't say anything helpful but there's an example of uploading a network file here:

https://github.com/leela-zero/leela-zero-server/blob/d8fe66acdb296cc1b82736203b3d7b4b02739ec1/server.js#L513

> curl -F 'weights=@zero.prototxt' -F 'training_count=175000' http://localhost:8080/submit-network

Of course you can change training_count to 0 or 1 or something super low since it's new. @filename is the network filename to add to server.

**Comment by Superkidd** [comment]
@roy7  So, I want to know how to connect autogtp with my local server.
in the autogtp/Management.cpp, 
I changed `const Qstring server_url = "https://zero.sjeng.org/`" to `"http://localhost:27017/"`
of course, I set a my **leela-zero-server** using mongodb. but it didn't work.  Could you give me a tutorial on what to do if I did something wrong?

**Comment by roy7** [comment]
Hmm I'm not sure. I wonder if https is required?

**Comment by roy7** [comment]
It looks like it mostly just feeds these commands/URLs to curl. So I'd think that should work. Do you get any sort of error message from autogtp? Do you see any log messages on the server side?

**Comment by Superkidd** [comment]
I included best network hash in 'network' directory of leela-server.
and, in turn, execute node server.js and autogtp.exe.

This is my autogtp error message 
![image](https://user-images.githubusercontent.com/35056082/57074225-3f4d7c80-6d1e-11e9-8257-7240a7d67b33.png)

This is my server.js message 
![image](https://user-images.githubusercontent.com/35056082/57074309-791e8300-6d1e-11e9-954c-ff2051bd9f46.png)

**Comment by roy7** [comment]
It appears autogtp isn't matching the hash of the file that the server says the hash should be. If it helps the hash should be calculated on the contents of the zip file, not the zip file itself. Try copying the file to a filename matching the hash listed in the autogtp message, and make that file the best network. Then the hashes will match and hopefully autogtp will proceed.

**Comment by Superkidd** [comment]
@roy7  When I checked the log **"Download network hash desen't match, calculated: 3ba11..."**,
I founded that this is related with the Autogtp/[Management.cpp](https://github.com/leela-zero/leela-zero/blob/next/autogtp/Management.cpp), line 540,  So I tested  **networkExists** function.
1) I want to check **result**, **gzipHash**
2) Whatever network file in my local server, result value is fixed.
3) Whatever network file in my local server, gzipHash value is empty.
4) So I just tested by Hard coding like,
![image](https://user-images.githubusercontent.com/35056082/57563220-45a2bf00-73d6-11e9-8e36-a62de94e793b.png)
5) it should not print Previous error messages".
But It doesn't work , and print another error message.

**" *ERROR*: Could not talk to engine after launching."**

I think that There are hints in **server.js** like your comment.
But I don't know exactly How can I insert the curl command, and where.
Could you explain plz?

**Comment by roy7** [comment]
You can upload a network to the server using a command like

>  curl -F 'weights=@filename' -F 'training_count=175000' -F 'key=password_in_auth_file' http://localhost:8080/submit-network

Where training_count is whatever counter you want to use. This will upload the file into the networks directory and add it into mongodb and calculate the hashes automatically. The file you upload can be copied to "best-network.gz" to effectively promote the network you uploaded as the new best network.

Here are some tiny scripts I use to make things easier when I need to do something manually.

$ cat request-match.sh
curl -F network1=$1 -F network2=$2 -F key=`cat auth_key` http://zero.sjeng.org/request-match

$ cat request-test.sh
curl -F is_test=1 -F network1=$1 -F network2=$2 -F key=`cat auth_key` http://zero.sjeng.org/request-match

I run those in the server directory so it reads auth_key and adds it to command line, then I can just do like "./request-match.sh hash1 hash2" to queue a match.

**Comment by roy7** [comment]
I see in your log "weights file is wrong version". I don't know what'd cause that. Also I don't see a hash_gzip_hash in your autogtp output. When I run autogtp myself in the directory it compiles in, I get:

> AutoGTP v18
> Using 1 game thread(s) per device.
> Starting tuning process, please wait...
> Net filename: networks/d42f950a8a9c82af5859e8698a5395c348c474708a7ada989d6af42d14e81b3f.gz
> net: d42f950a8a9c82af5859e8698a5395c348c474708a7ada989d6af42d14e81b3f.
> ./leelaz --batchsize=5 --tune-only -w networks/d42f950a8a9c82af5859e8698a5395c348c474708a7ada989d6af42d14e81b3f.gz
> Found Leela Version :
> Tuning process finished
> Starting thread 1 on device 0
> {
>     "cmd": "selfplay",
>     "hash": "d42f950a8a9c82af5859e8698a5395c348c474708a7ada989d6af42d14e81b3f",
>     "hash_gzip_hash": "a1a43e9bd556f3094cfa08c9e4b0605a36a2022cd719965425e5c17d4d1bd56f",
>     "minimum_autogtp_version": "16",
>     "minimum_leelaz_version": "0.15",
>     "options": {
>         "noise": "true",
>         "playouts": "0",
>         "randomcnt": "30",
>         "resignation_percent": "5",
>         "visits": "1601"
>     },
>     "options_hash": "0042e8",
>     "random_seed": "2751924546131346435",
>     "required_client_version": "16"
> }
> 
> Got new job: selfplay
> net: d42f950a8a9c82af5859e8698a5395c348c474708a7ada989d6af42d14e81b3f.
> *ERROR*: No 'leelaz' binary found.

Maybe you need to do a git pull and pop into src/autogtp and run a fresh 'make' command?

**Comment by roy7** [comment]
When I say "zip file" I mean compressed with gzip, not literal zip.

**Comment by Superkidd** [comment]
@roy7  Okay, I do all of things that  you already explained e.g, curl command. So I got output 
![image](https://user-images.githubusercontent.com/35056082/58382268-4f960600-8003-11e9-9f8c-fea83acf27d5.png).

but , continuously, I have same problem on autogtp.
When I executed autogtp, I just clicked autogtp.exe in here.
![image](https://user-images.githubusercontent.com/35056082/58382365-33469900-8004-11e9-8401-989485052e78.png)


And I have a log message .
![image](https://user-images.githubusercontent.com/35056082/58382315-c501d680-8003-11e9-8d68-d6cdbf2b9481.png)


So, how can I play a match with autogtp after uploading the network and match to the server with the curl command? I confused.

**Comment by roy7** [comment]
The only thing I can guess is that you have a network in the database with the wrong hash. When you upload a network to the curl command the server will calculate the hash and store that as the network file name. It will when Auto GTP downloads it it will compare hashes to make sure they match. The server and the client should be calculating the hash the same way. 

So all I can guess is that maybe you added a network by hand into the database but put in the wrong hash? They use the hash of the actual network, not the gzip file.

Maybe upload a second Network, set up a match between them, and delete the older matches from the database? That should try to do a match between two networks you uploaded through curl and I have to hope that would work.

**Comment by roy7** [comment]
Another thing you could try is renaming the network in the database to the same hash that the log says it's supposed to be. And then rename the file name too.

**Comment by Superkidd** [comment]
I think that this is the key, **So all I can guess is that maybe you added a network by hand into the database but put in the wrong hash** What is that meaning?
I just use Curl commands to upload a network and match in server but not database.
Specifically, I uploaded two networks to the server using the curl command, and I could see two network files e.g, d42..(bla bla).gz,  a20....(bla bla).gz in the leela-zero-server / network directory. Then I copied the first uploaded network file and changed its name to best-network.gz.

And when I checked mongoDB logs , all of things I've done was saved. 
Is this related to that you said?

**Comment by roy7** [comment]
It doesn't sound like you've done anything wrong but the client thinks your d42f file has a hash of 3ba1 instead of d42f. autogtp won't proceed if the hashes don't match since it means there is some sort of an error.

Please try this command on each of your network gzip files and see if the hashes match the file name:

```[roy@ryzen-one src]$ zcat c910dee9c057d144efaafb603ce69d564825ca316dd8129ce0f05c1231d1f9bc.gz | sha256sum
c910dee9c057d144efaafb603ce69d564825ca316dd8129ce0f05c1231d1f9bc  -
```

**Comment by roy7** [comment]
If zcat on d42.gz prints 3ba1 then autogtp is correct and that file is wrong in the database/upload somehow. If the hashes are correct then it's an issue on the autogtp side.

**Comment by Superkidd** [comment]
@roy7 
When I run autogtp.exe, the weight file on the server side is not completely passed(e.g 3kb is passed).

What I discovered when I debugged autogtp was that gziphash(in autogtp/management.cpp) did not contain any values. So I think that 'gziphash' is a calculated hash value by the server, and result is a hash value calculated by autogtp on the weight file received from the server. Is that correct?

So, as a result, autogtp can not get the weight file from the server perfectly, so the result value is 3ba ...
gziphash seems to be a null value.

...... Why autogtp cannot get network files perfectly from the server?
I think it's a version issue. Could it be a problem if I use leela zero 0.17 + autogtp v18?

**Comment by roy7** [comment]
Look at the file it did download and see if it is like a web page error message or something.

Yeah we moved to gzip hashes on downloading to reduce overhead that autogtp doesnt have to unzip the file every time. You should be using latest version of the server code and leela zero. Like the next branch from each.

**Comment by Superkidd** [comment]
@roy7  okay when I use next branch from each, 
```
D:\leela-zero\msvc\x64\Release>autogtp.exe
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Downloaded network hash doesn't match, calculated: dd4cec1684570d06e19baf9ffadcb5f7df773159275ea6aac6423576c4fb1785 it should be: 8b10a7b6ee613eaec1b0d0807ca7900f6711f12bfe44e3b02d944901fa5b52a7
Net filename: networks/a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82.gz
net: a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82.
./leelaz --batchsize=5 --tune-only -w networks/a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82.gz
Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 6619147284182967105
BLAS Core: built-in Eigen 3.3.7 library.
Weights file is the wrong version.
Found Leela Version : 0.17
Tuning process finished
Starting thread 1 on device 0
{
    "cmd": "selfplay",
    "hash": "a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82",
    "hash_gzip_hash": "8b10a7b6ee613eaec1b0d0807ca7900f6711f12bfe44e3b02d944901fa5b52a7",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "30",
        "resignation_percent": "5",
        "visits": "1601"
    },
    "options_hash": "0042e8",
    "random_seed": "4697124060649139817",
    "required_client_version": "16"
}

Got new job: selfplay
Downloaded network hash doesn't match, calculated: dd4cec1684570d06e19baf9ffadcb5f7df773159275ea6aac6423576c4fb1785 it should be: 8b10a7b6ee613eaec1b0d0807ca7900f6711f12bfe44e3b02d944901fa5b52a7
Net filename: networks/a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82.gz
net: a20c31da0db23da6efc16739b2e62b058b2ff86060512c58ef6fefe14a0e2a82.
*ERROR*: Could not talk to engine after launching.

```
From now on,  I have a gziphash value correctly but still I cannot get the 'result' value correctly.
so, it doesn't match.
do you have any comment plz?

**Comment by Superkidd** [comment]
oh I solved the problem..

**Comment by roy7** [comment]
What fixed it? Yay!

**Comment by Superkidd** [comment]
Your all comment is helpful for me.
@roy7 
I have a one more question.
what is different selfplay and matches in detail.
and How can I play a matches uploaded on server ?

**Comment by roy7** [comment]
If you want to see matches uploaded to the server you can click the "VS" on the home page where the match is listed, it should show you all the games that were played.

I'm not sure on your other question, but basically selfplay uses the best network to play itself and generate training games to use for the training step. Matches are just to compare networks and promote a stronger network if it beats the current best network. Matches can also be set as a 'test' so there will be no promotion even if it does well.

**Comment by roy7** [comment]
Is this issue ready to be closed @Superkidd?

**Comment by roy7** [comment]
If nothing else, the hash mismatch error is fixed in https://github.com/leela-zero/leela-zero-server/pull/227 since the server didn't know how to serve the network files for download.
