### ISSUE TITLE
Never starts playing games

### ISSUE THREAD

**Issue by DonMathi** [leela-zero/leela-zero-server#218]
I just downloaded the latest version Leela Zero 0.17 + AutoGTP v18, because I would like to participate. But the computer never starts playing any games
It continues to linger after reveiving a game to play??

C:\bla bla path\>autogtp.exe -k games
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Net filename: networks/c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d.gz
net: c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d.
./leelaz --batchsize=5 --tune-only -w networks/c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d.gz
Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 1479662456122220460
BLAS Core: Sandybridge
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  2600 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.5059
Device speed:  1200 MHz
Device cores:  16 CU
Device score:  612
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4000
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: No.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  2600 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.5059
Device speed:  1200 MHz
Device cores:  16 CU
Device score:  612
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4000
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: No.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=2 12.8508 ms (45.9 GFLOPS)
(3/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=4 12.1232 ms (48.7 GFLOPS)
(12/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=4 8.8027 ms (67.0 GFLOPS)
(17/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=2 8.6381 ms (68.3 GFLOPS)
(18/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=2 VWN=4 6.7141 ms (87.8 GFLOPS)
(44/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=4 6.5805 ms (89.6 GFLOPS)
(48/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=2 VWN=4 6.0578 ms (97.4 GFLOPS)
(74/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=4 4.8756 ms (121.0 GFLOPS)
Found Leela Version : 0.17
Tuning process finished
Starting thread 1 on device 0
{
    "cmd": "selfplay",
    "hash": "c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d",
    "hash_gzip_hash": "84256e3f92c297a8770675451bf5240b7d560c4190463fb1a986455af2182ab8",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "30",
        "resignation_percent": "5",
        "visits": "1601"
    },
    "options_hash": "0042e8",
    "random_seed": "8361045903632941110",
    "required_client_version": "16"
}

Got new job: selfplay
net: c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d.

**Comment by roy7** [comment]
You may need to post and ask on the LZ client github. It seems like everything was fine down to the point it got the selfplay request. Did it download the net into your folder?

**Comment by DonMathi** [comment]
Yes it loads the new net into the networks subfolder.
When I start it, it remains at the point:
Got new job: selfplay
net: c9fb22c70c0d43c96102b1bb06043510eea3d4f8da1bde3ddaadafdff2a6da5d.

And the CPU is running with about 30% load on the leelaz application
But it never starts playing

**Comment by DonMathi** [comment]
Moved to application
